version: "3.7"

x-app-variables: &app-variables
  DB_URI: mongodb://user:1234@jornada-milhas-db:27017/jornada-milhas-db
  OPEN_AI_TOKEN: <seu-token-open-ai>
x-mongo-variables: &mongodb-variables
  MONGO_INITDB_DATABASE: jornada-milhas-db
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: 1234

services:
  db:
    image: mongo
    container_name: jornada-milhas-db
    ports:
      - "27017:27017"
    environment:
      <<: *mongodb-variables
    volumes:
      - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"

  app:
    image: edsonmendes/jornada-milhas-api:v0.3
    container_name: jornada-milhas-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      <<: *app-variables
