version: '3.1'

services:
  db:
    image: mongo
    container_name: jornada-milhas-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: jornada-milhas-db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"