spring:
  data:
    mongodb:
      uri: mongodb://user:1234@localhost:27017/jornada-milhas-db

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG