server:
  port: ${PORT:8080}

# Datasource properties
spring:
  data:
    mongodb:
      uri: ${DB_URI:mongodb://user:1234@localhost:27017/jornada-milhas-db}

# Multipart properties
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

# Security properties
  security:
    oauth2:
      client:
        registration:
          google:
            client_id: ${CLIENT_ID}
            client_secret: ${CLIENT_SECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

# Environment variable
jornadamilhas:
  openai:
    token: ${OPEN_AI_TOKEN}

# Springdoc properties
springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha

# Logging properties
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG