# Datasource properties
spring:
  data:
    mongodb:
      uri: mongodb://user:1234@localhost:27017/jornada-milhas-db

# Multipart properties
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

jornadamilhas:
  openai:
    token: ${OPEN_AI_TOKEN}

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG