# Datasource properties
spring:
  data:
    mongodb:
      uri: mongodb://user:1234@localhost:27017/jornada-milhas-db

# Multipart properties
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

# Environment variable
jornadamilhas:
  openai:
    token: ${OPEN_AI_TOKEN}

# Springdoc properties
springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha

# Logging properties
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG